parameters:
    # ... other parameters
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login                
                check_path:     sonata_user_admin_security_check
                failure_path:   sonata_user_admin_security_login
                use_forward:    false
                use_referer:    true
            logout:
                path:           sonata_user_admin_security_logout
                target:         sonata_user_admin_security_login            
            anonymous:          true

        # -> end custom configuration
        # defaut login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     sonata_user_admin_security_check
                failure_path:   null
                default_target_path: sonata_admin_dashboard
            logout:             true
            anonymous:          true

    
    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/\w\w/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/\w\w/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/\w\w/admin/via/user/, role: ['ROLE_ADMIN', 'ROLE_SONATA_ADMIN'] }
        - { path: ^/\w\w/admin/, role: ['ROLE_USER', 'ROLE_ADMIN', 'ROLE_SONATA_ADMIN'] }
        
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default