
via_api_via_ebay_test:
    pattern: /viaebay/test/
    methods: [GET]
    defaults:
        _controller: via_api.controller.viaebay.test:indexAction
        _via:            
            #method: createFilterPaginator
            arguments: ['$criteria', '$sorting', '$deleted'] 